//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab02_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public string MaVe { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
